title: homewizard4j
description: Unofficial Java API for HomeWizard devices
theme: just-the-docs

url: https://thijzert123.github.io/homewizard4j

aux_links:
  GitHub Repository: https://github.com/Thijzert123/homewizard4j
